/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 20 15:40:23 CET 2016
 */
package org.exoplatform.salesforce.integ.connector.entity;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Contact_Status__c
 */
public enum Contact_StatusEnum {

    // Cloud user
    CLOUD_USER("Cloud user"),
    // Cold
    COLD("Cold"),
    // Community user
    COMMUNITY_USER("Community user"),
    // Customer
    CUSTOMER("Customer"),
    // Nurturing
    NURTURING("Nurturing"),
    // Opportunity
    OPPORTUNITY("Opportunity"),
    // Qualified
    QUALIFIED("Qualified"),
    // Re-qualified
    RE_QUALIFIED("Re-qualified"),
    // Recycle
    RECYCLE("Recycle");

    final String value;

    private Contact_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Contact_StatusEnum fromValue(String value) {
        for (Contact_StatusEnum e : Contact_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
