/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 20 15:40:23 CET 2016
 */
package org.exoplatform.salesforce.integ.connector.entity;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.exoplatform.salesforce.integ.util.PicklistEnumConverter;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject Contact
 */
@JsonIgnoreProperties(ignoreUnknown=true)
@XStreamAlias("Contact")
public class Contact {

    private String id;

    @JsonProperty("Id")
    public String getId() {
        return this.id;
    }

    // LastName
    private String LastName;

    @JsonProperty("LastName")
    public String getLastName() {
        return this.LastName;
    }

    @JsonProperty("LastName")
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    // FirstName
    private String FirstName;

    @JsonProperty("FirstName")
    public String getFirstName() {
        return this.FirstName;
    }

    @JsonProperty("FirstName")
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    // Email
    private String Email;

    @JsonProperty("Email")
    public String getEmail() {
        return this.Email;
    }

    @JsonProperty("Email")
    public void setEmail(String Email) {
        this.Email = Email;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // Contact_Status__c
    @XStreamConverter(PicklistEnumConverter.class)
    private Contact_StatusEnum Contact_Status__c;

    @JsonProperty("Contact_Status__c")
    public Contact_StatusEnum getContact_Status__c() {
        return this.Contact_Status__c;
    }

    @JsonProperty("Contact_Status__c")
    public void setContact_Status__c(Contact_StatusEnum Contact_Status__c) {
        this.Contact_Status__c = Contact_Status__c;
    }

    // Timezone__c
    @XStreamConverter(PicklistEnumConverter.class)
    private TimezoneEnum Timezone__c;

    @JsonProperty("Timezone__c")
    public TimezoneEnum getTimezone__c() {
        return this.Timezone__c;
    }

    @JsonProperty("Timezone__c")
    public void setTimezone__c(TimezoneEnum Timezone__c) {
        this.Timezone__c = Timezone__c;
    }

    // AccountId
    private String AccountId;

    @JsonProperty("AccountId")
    public String getAccountId() {
        return this.AccountId;
    }

    @JsonProperty("AccountId")
    public void setAccountId(String AccountId) {
        this.AccountId = AccountId;
    }

}
