/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon May 09 18:02:06 CET 2016
 */
package org.exoplatform.salesforce.integ.connector.entity;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Lead_Country__c
 */
public enum Lead_CountryEnum {

    // Afghanistan
    AFGHANISTAN("Afghanistan"),
    // Albania
    ALBANIA("Albania"),
    // Algeria
    ALGERIA("Algeria"),
    // American Samoa
    AMERICAN_SAMOA("American Samoa"),
    // Andorra
    ANDORRA("Andorra"),
    // Angola
    ANGOLA("Angola"),
    // Anguilla
    ANGUILLA("Anguilla"),
    // Antarctica
    ANTARCTICA("Antarctica"),
    // Antigua & Barbuda
    ANTIGUA___BARBUDA("Antigua & Barbuda"),
    // Argentina
    ARGENTINA("Argentina"),
    // Armenia
    ARMENIA("Armenia"),
    // Aruba
    ARUBA("Aruba"),
    // Ascension Island
    ASCENSION_ISLAND("Ascension Island"),
    // Australia
    AUSTRALIA("Australia"),
    // Austria
    AUSTRIA("Austria"),
    // Azerbaijan
    AZERBAIJAN("Azerbaijan"),
    // Bahamas
    BAHAMAS("Bahamas"),
    // Bahrain
    BAHRAIN("Bahrain"),
    // Bangladesh
    BANGLADESH("Bangladesh"),
    // Barbados
    BARBADOS("Barbados"),
    // Belarus
    BELARUS("Belarus"),
    // Belgium
    BELGIUM("Belgium"),
    // Belize
    BELIZE("Belize"),
    // Benin
    BENIN("Benin"),
    // Bermuda
    BERMUDA("Bermuda"),
    // Bhutan
    BHUTAN("Bhutan"),
    // Bolivia
    BOLIVIA("Bolivia"),
    // Bosnia & Herzegovina
    BOSNIA___HERZEGOVINA("Bosnia & Herzegovina"),
    // Botswana
    BOTSWANA("Botswana"),
    // Brazil
    BRAZIL("Brazil"),
    // Brunei
    BRUNEI("Brunei"),
    // Bulgaria
    BULGARIA("Bulgaria"),
    // Burkina Faso
    BURKINA_FASO("Burkina Faso"),
    // Burundi
    BURUNDI("Burundi"),
    // Cambodia
    CAMBODIA("Cambodia"),
    // Cameroon
    CAMEROON("Cameroon"),
    // Canada
    CANADA("Canada"),
    // Cape Verde
    CAPE_VERDE("Cape Verde"),
    // Cayman Islands
    CAYMAN_ISLANDS("Cayman Islands"),
    // Central African Republic
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    // Chad
    CHAD("Chad"),
    // Chile
    CHILE("Chile"),
    // China
    CHINA("China"),
    // Christmas Island
    CHRISTMAS_ISLAND("Christmas Island"),
    // Cocos Islands
    COCOS_ISLANDS("Cocos Islands"),
    // Colombia
    COLOMBIA("Colombia"),
    // Comoros
    COMOROS("Comoros"),
    // Congo
    CONGO("Congo"),
    // Congo (Dem Rep of)
    CONGO__DEM_REP_OF_("Congo (Dem Rep of)"),
    // Cook Islands
    COOK_ISLANDS("Cook Islands"),
    // Costa Rica
    COSTA_RICA("Costa Rica"),
    // Croatia
    CROATIA("Croatia"),
    // Cuba
    CUBA("Cuba"),
    // Cyprus
    CYPRUS("Cyprus"),
    // Czech Republic
    CZECH_REPUBLIC("Czech Republic"),
    // Denmark
    DENMARK("Denmark"),
    // Djibouti
    DJIBOUTI("Djibouti"),
    // Dominica
    DOMINICA("Dominica"),
    // Dominican Republic
    DOMINICAN_REPUBLIC("Dominican Republic"),
    // East Timor
    EAST_TIMOR("East Timor"),
    // Ecuador
    ECUADOR("Ecuador"),
    // Egypt
    EGYPT("Egypt"),
    // El Salvador
    EL_SALVADOR("El Salvador"),
    // Equatorial Guinea
    EQUATORIAL_GUINEA("Equatorial Guinea"),
    // Eritrea
    ERITREA("Eritrea"),
    // Estonia
    ESTONIA("Estonia"),
    // Ethiopia
    ETHIOPIA("Ethiopia"),
    // Falkland Islands
    FALKLAND_ISLANDS("Falkland Islands"),
    // Faroe Islands
    FAROE_ISLANDS("Faroe Islands"),
    // Fiji
    FIJI("Fiji"),
    // Finland
    FINLAND("Finland"),
    // France
    FRANCE("France"),
    // French Guiana
    FRENCH_GUIANA("French Guiana"),
    // French Polynesia
    FRENCH_POLYNESIA("French Polynesia"),
    // French Southern Territories
    FRENCH_SOUTHERN_TERRITORIES("French Southern Territories"),
    // Gabon
    GABON("Gabon"),
    // Gambia
    GAMBIA("Gambia"),
    // Georgia
    GEORGIA("Georgia"),
    // Germany
    GERMANY("Germany"),
    // Ghana
    GHANA("Ghana"),
    // Gibraltar
    GIBRALTAR("Gibraltar"),
    // Greece
    GREECE("Greece"),
    // Greenland
    GREENLAND("Greenland"),
    // Grenada
    GRENADA("Grenada"),
    // Guadeloupe
    GUADELOUPE("Guadeloupe"),
    // Guam
    GUAM("Guam"),
    // Guatemala
    GUATEMALA("Guatemala"),
    // Guinea
    GUINEA("Guinea"),
    // Guinea-Bissau
    GUINEA_BISSAU("Guinea-Bissau"),
    // Guyana
    GUYANA("Guyana"),
    // Haiti
    HAITI("Haiti"),
    // Honduras
    HONDURAS("Honduras"),
    // Hong Kong
    HONG_KONG("Hong Kong"),
    // Hungary
    HUNGARY("Hungary"),
    // Iceland
    ICELAND("Iceland"),
    // India
    INDIA("India"),
    // Indonesia
    INDONESIA("Indonesia"),
    // Iran
    IRAN("Iran"),
    // Iraq
    IRAQ("Iraq"),
    // Ireland
    IRELAND("Ireland"),
    // Israel
    ISRAEL("Israel"),
    // Italy
    ITALY("Italy"),
    // Ivory Coast
    IVORY_COAST("Ivory Coast"),
    // Jamaica
    JAMAICA("Jamaica"),
    // Japan
    JAPAN("Japan"),
    // Jordan
    JORDAN("Jordan"),
    // Kazakhstan
    KAZAKHSTAN("Kazakhstan"),
    // Kenya
    KENYA("Kenya"),
    // Kiribati
    KIRIBATI("Kiribati"),
    // Korea (North)
    KOREA__NORTH_("Korea (North)"),
    // Korea (South)
    KOREA__SOUTH_("Korea (South)"),
    // Kosovo
    KOSOVO("Kosovo"),
    // Kuwait
    KUWAIT("Kuwait"),
    // Kyrgyzstan
    KYRGYZSTAN("Kyrgyzstan"),
    // Laos
    LAOS("Laos"),
    // Latvia
    LATVIA("Latvia"),
    // Lebanon
    LEBANON("Lebanon"),
    // Lesotho
    LESOTHO("Lesotho"),
    // Liberia
    LIBERIA("Liberia"),
    // Libya
    LIBYA("Libya"),
    // Liechtenstein
    LIECHTENSTEIN("Liechtenstein"),
    // Lithuania
    LITHUANIA("Lithuania"),
    // Luxembourg
    LUXEMBOURG("Luxembourg"),
    // Macao
    MACAO("Macao"),
    // Macedonia
    MACEDONIA("Macedonia"),
    // Madagascar
    MADAGASCAR("Madagascar"),
    // Malawi
    MALAWI("Malawi"),
    // Malaysia
    MALAYSIA("Malaysia"),
    // Maldives
    MALDIVES("Maldives"),
    // Mali
    MALI("Mali"),
    // Malta
    MALTA("Malta"),
    // Marshall Islands
    MARSHALL_ISLANDS("Marshall Islands"),
    // Martinique
    MARTINIQUE("Martinique"),
    // Mauritania
    MAURITANIA("Mauritania"),
    // Mauritius
    MAURITIUS("Mauritius"),
    // Mayotte
    MAYOTTE("Mayotte"),
    // Mexico
    MEXICO("Mexico"),
    // Micronesia (Fed States of)
    MICRONESIA__FED_STATES_OF_("Micronesia (Fed States of)"),
    // Moldova
    MOLDOVA("Moldova"),
    // Monaco
    MONACO("Monaco"),
    // Mongolia
    MONGOLIA("Mongolia"),
    // Montenegro
    MONTENEGRO("Montenegro"),
    // Montserrat
    MONTSERRAT("Montserrat"),
    // Morocco
    MOROCCO("Morocco"),
    // Mozambique
    MOZAMBIQUE("Mozambique"),
    // Myanmar
    MYANMAR("Myanmar"),
    // Namibia
    NAMIBIA("Namibia"),
    // Nauru
    NAURU("Nauru"),
    // Nepal
    NEPAL("Nepal"),
    // Netherlands
    NETHERLANDS("Netherlands"),
    // Netherlands Antilles
    NETHERLANDS_ANTILLES("Netherlands Antilles"),
    // New Caledonia
    NEW_CALEDONIA("New Caledonia"),
    // New Zealand
    NEW_ZEALAND("New Zealand"),
    // Nicaragua
    NICARAGUA("Nicaragua"),
    // Niger
    NIGER("Niger"),
    // Nigeria
    NIGERIA("Nigeria"),
    // Niue
    NIUE("Niue"),
    // Norfolk Island
    NORFOLK_ISLAND("Norfolk Island"),
    // Northern Mariana Islands
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands"),
    // Norway
    NORWAY("Norway"),
    // Oman
    OMAN("Oman"),
    // Pakistan
    PAKISTAN("Pakistan"),
    // Palau
    PALAU("Palau"),
    // Palestinian Territory
    PALESTINIAN_TERRITORY("Palestinian Territory"),
    // Panama
    PANAMA("Panama"),
    // Papua New Guinea
    PAPUA_NEW_GUINEA("Papua New Guinea"),
    // Paraguay
    PARAGUAY("Paraguay"),
    // Peru
    PERU("Peru"),
    // Philippines
    PHILIPPINES("Philippines"),
    // Poland
    POLAND("Poland"),
    // Portugal
    PORTUGAL("Portugal"),
    // Puerto Rico
    PUERTO_RICO("Puerto Rico"),
    // Qatar
    QATAR("Qatar"),
    // Reunion
    REUNION("Reunion"),
    // Romania
    ROMANIA("Romania"),
    // Russian Federation
    RUSSIAN_FEDERATION("Russian Federation"),
    // Rwanda
    RWANDA("Rwanda"),
    // Samoa
    SAMOA("Samoa"),
    // Sao Tome & Principe
    SAO_TOME___PRINCIPE("Sao Tome & Principe"),
    // Saudi Arabia
    SAUDI_ARABIA("Saudi Arabia"),
    // Senegal
    SENEGAL("Senegal"),
    // Serbia
    SERBIA("Serbia"),
    // Seychelles
    SEYCHELLES("Seychelles"),
    // Sierra Leone
    SIERRA_LEONE("Sierra Leone"),
    // Singapore
    SINGAPORE("Singapore"),
    // Slovakia
    SLOVAKIA("Slovakia"),
    // Slovenia
    SLOVENIA("Slovenia"),
    // Solomon Islands
    SOLOMON_ISLANDS("Solomon Islands"),
    // Somalia
    SOMALIA("Somalia"),
    // South Africa
    SOUTH_AFRICA("South Africa"),
    // Spain
    SPAIN("Spain"),
    // Sri Lanka
    SRI_LANKA("Sri Lanka"),
    // St Helena
    ST_HELENA("St Helena"),
    // St Kitts & Nevis
    ST_KITTS___NEVIS("St Kitts & Nevis"),
    // St Lucia
    ST_LUCIA("St Lucia"),
    // St Martin
    ST_MARTIN("St Martin"),
    // St Pierre & Miquelon
    ST_PIERRE___MIQUELON("St Pierre & Miquelon"),
    // St Vincent & the Grenadines
    ST_VINCENT___THE_GRENADINES("St Vincent & the Grenadines"),
    // Sudan
    SUDAN("Sudan"),
    // Suriname
    SURINAME("Suriname"),
    // Swaziland
    SWAZILAND("Swaziland"),
    // Sweden
    SWEDEN("Sweden"),
    // Switzerland
    SWITZERLAND("Switzerland"),
    // Syria
    SYRIA("Syria"),
    // Taiwan
    TAIWAN("Taiwan"),
    // Tajikistan
    TAJIKISTAN("Tajikistan"),
    // Tanzania
    TANZANIA("Tanzania"),
    // Thailand
    THAILAND("Thailand"),
    // Togo
    TOGO("Togo"),
    // Tonga
    TONGA("Tonga"),
    // Trinidad & Tobago
    TRINIDAD___TOBAGO("Trinidad & Tobago"),
    // Tristan da Cunha
    TRISTAN_DA_CUNHA("Tristan da Cunha"),
    // Tunisia
    TUNISIA("Tunisia"),
    // Turkey
    TURKEY("Turkey"),
    // Turkmenistan
    TURKMENISTAN("Turkmenistan"),
    // Turks & Caicos Islands
    TURKS___CAICOS_ISLANDS("Turks & Caicos Islands"),
    // Tuvalu
    TUVALU("Tuvalu"),
    // Uganda
    UGANDA("Uganda"),
    // Ukraine
    UKRAINE("Ukraine"),
    // United Arab Emirates
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    // United Kingdom
    UNITED_KINGDOM("United Kingdom"),
    // United States
    UNITED_STATES("United States"),
    // Uruguay
    URUGUAY("Uruguay"),
    // Uzbekistan
    UZBEKISTAN("Uzbekistan"),
    // Vanuatu
    VANUATU("Vanuatu"),
    // Venezuela
    VENEZUELA("Venezuela"),
    // Vietnam
    VIETNAM("Vietnam"),
    // Virgin Islands (British)
    VIRGIN_ISLANDS__BRITISH_("Virgin Islands (British)"),
    // Virgin Islands (US)
    VIRGIN_ISLANDS__US_("Virgin Islands (US)"),
    // Western Sahara
    WESTERN_SAHARA("Western Sahara"),
    // Yemen
    YEMEN("Yemen"),
    // Zambia
    ZAMBIA("Zambia"),
    // Zimbabwe
    ZIMBABWE("Zimbabwe");

    final String value;

    private Lead_CountryEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Lead_CountryEnum fromValue(String value) {
        for (Lead_CountryEnum e : Lead_CountryEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
