/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon May 09 18:02:06 CET 2016
 */
package org.exoplatform.salesforce.integ.connector.entity;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.exoplatform.salesforce.integ.util.PicklistEnumConverter;
import org.codehaus.jackson.annotate.JsonProperty;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

/**
 * Salesforce DTO for SObject Lead
 */
@JsonIgnoreProperties(ignoreUnknown=true)
@XStreamAlias("Lead")
public class Lead {

    private String id;

    @JsonProperty("Id")
    public String getId() {
        return this.id;
    }

    private String OwnerId;

    @JsonProperty("OwnerId")
    public String getOwnerId() {
        return this.OwnerId;
    }

    @JsonProperty("OwnerId")
    public void setOwnerId(String ownerId) {
        this.OwnerId = ownerId;
    }

    // MasterRecordId
    private String MasterRecordId;

    @JsonProperty("MasterRecordId")
    public String getMasterRecordId() {
        return this.MasterRecordId;
    }

    @JsonProperty("MasterRecordId")
    public void setMasterRecordId(String MasterRecordId) {
        this.MasterRecordId = MasterRecordId;
    }

    // LastName
    private String LastName;

    @JsonProperty("LastName")
    public String getLastName() {
        return this.LastName;
    }

    @JsonProperty("LastName")
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    // FirstName
    private String FirstName;

    @JsonProperty("FirstName")
    public String getFirstName() {
        return this.FirstName;
    }

    @JsonProperty("FirstName")
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    // Title
    private String Title;

    @JsonProperty("Title")
    public String getTitle() {
        return this.Title;
    }

    @JsonProperty("Title")
    public void setTitle(String Title) {
        this.Title = Title;
    }

    // Company
    private String Company;

    @JsonProperty("Company")
    public String getCompany() {
        return this.Company;
    }

    @JsonProperty("Company")
    public void setCompany(String Company) {
        this.Company = Company;
    }

    // Street
    private String Street;

    @JsonProperty("Street")
    public String getStreet() {
        return this.Street;
    }

    @JsonProperty("Street")
    public void setStreet(String Street) {
        this.Street = Street;
    }

    // City
    private String City;

    @JsonProperty("City")
    public String getCity() {
        return this.City;
    }

    @JsonProperty("City")
    public void setCity(String City) {
        this.City = City;
    }

    // State
    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    // PostalCode
    private String PostalCode;

    @JsonProperty("PostalCode")
    public String getPostalCode() {
        return this.PostalCode;
    }

    @JsonProperty("PostalCode")
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    // Country
    private String Country;

    @JsonProperty("Country")
    public String getCountry() {
        return this.Country;
    }

    @JsonProperty("Country")
    public void setCountry(String Country) {
        this.Country = Country;
    }

    // Latitude
    private Double Latitude;

    @JsonProperty("Latitude")
    public Double getLatitude() {
        return this.Latitude;
    }

    @JsonProperty("Latitude")
    public void setLatitude(Double Latitude) {
        this.Latitude = Latitude;
    }

    // Longitude
    private Double Longitude;

    @JsonProperty("Longitude")
    public Double getLongitude() {
        return this.Longitude;
    }

    @JsonProperty("Longitude")
    public void setLongitude(Double Longitude) {
        this.Longitude = Longitude;
    }

    // Phone
    private String Phone;

    @JsonProperty("Phone")
    public String getPhone() {
        return this.Phone;
    }

    @JsonProperty("Phone")
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    // Email
    private String Email;

    @JsonProperty("Email")
    public String getEmail() {
        return this.Email;
    }

    @JsonProperty("Email")
    public void setEmail(String Email) {
        this.Email = Email;
    }

    // Website
    private String Website;

    @JsonProperty("Website")
    public String getWebsite() {
        return this.Website;
    }

    @JsonProperty("Website")
    public void setWebsite(String Website) {
        this.Website = Website;
    }

    // PhotoUrl
    private String PhotoUrl;

    @JsonProperty("PhotoUrl")
    public String getPhotoUrl() {
        return this.PhotoUrl;
    }

    @JsonProperty("PhotoUrl")
    public void setPhotoUrl(String PhotoUrl) {
        this.PhotoUrl = PhotoUrl;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // Status
    @XStreamConverter(PicklistEnumConverter.class)
    private StatusEnum Status;

    @JsonProperty("Status")
    public StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(StatusEnum Status) {
        this.Status = Status;
    }

    // Rating
    @XStreamConverter(PicklistEnumConverter.class)
    private RatingEnum Rating;

    @JsonProperty("Rating")
    public RatingEnum getRating() {
        return this.Rating;
    }

    @JsonProperty("Rating")
    public void setRating(RatingEnum Rating) {
        this.Rating = Rating;
    }

    // Lead_Country__c
    @XStreamConverter(PicklistEnumConverter.class)
    private Lead_CountryEnum Lead_Country__c;

    @JsonProperty("Lead_Country__c")
    public Lead_CountryEnum getLead_Country__c() {
        return this.Lead_Country__c;
    }

    @JsonProperty("Lead_Country__c")
    public void setLead_Country__c(Lead_CountryEnum Lead_Country__c) {
        this.Lead_Country__c = Lead_Country__c;
    }

    // CurrencyIsoCode
    @XStreamConverter(PicklistEnumConverter.class)
    private CurrencyIsoCodeEnum CurrencyIsoCode;

    @JsonProperty("CurrencyIsoCode")
    public CurrencyIsoCodeEnum getCurrencyIsoCode() {
        return this.CurrencyIsoCode;
    }

    @JsonProperty("CurrencyIsoCode")
    public void setCurrencyIsoCode(CurrencyIsoCodeEnum CurrencyIsoCode) {
        this.CurrencyIsoCode = CurrencyIsoCode;
    }

    // AnnualRevenue
    private Double AnnualRevenue;

    @JsonProperty("AnnualRevenue")
    public Double getAnnualRevenue() {
        return this.AnnualRevenue;
    }

    @JsonProperty("AnnualRevenue")
    public void setAnnualRevenue(Double AnnualRevenue) {
        this.AnnualRevenue = AnnualRevenue;
    }

    // NumberOfEmployees
    private Integer NumberOfEmployees;

    @JsonProperty("NumberOfEmployees")
    public Integer getNumberOfEmployees() {
        return this.NumberOfEmployees;
    }

    @JsonProperty("NumberOfEmployees")
    public void setNumberOfEmployees(Integer NumberOfEmployees) {
        this.NumberOfEmployees = NumberOfEmployees;
    }

    // HasOptedOutOfEmail
    private Boolean HasOptedOutOfEmail;

    @JsonProperty("HasOptedOutOfEmail")
    public Boolean getHasOptedOutOfEmail() {
        return this.HasOptedOutOfEmail;
    }

    @JsonProperty("HasOptedOutOfEmail")
    public void setHasOptedOutOfEmail(Boolean HasOptedOutOfEmail) {
        this.HasOptedOutOfEmail = HasOptedOutOfEmail;
    }

    // IsConverted
    private Boolean IsConverted;

    @JsonProperty("IsConverted")
    public Boolean getIsConverted() {
        return this.IsConverted;
    }

    @JsonProperty("IsConverted")
    public void setIsConverted(Boolean IsConverted) {
        this.IsConverted = IsConverted;
    }

    // ConvertedDate
    private org.joda.time.DateTime ConvertedDate;

    @JsonProperty("ConvertedDate")
    public org.joda.time.DateTime getConvertedDate() {
        return this.ConvertedDate;
    }

    @JsonProperty("ConvertedDate")
    public void setConvertedDate(org.joda.time.DateTime ConvertedDate) {
        this.ConvertedDate = ConvertedDate;
    }

    // ConvertedAccountId
    private String ConvertedAccountId;

    @JsonProperty("ConvertedAccountId")
    public String getConvertedAccountId() {
        return this.ConvertedAccountId;
    }

    @JsonProperty("ConvertedAccountId")
    public void setConvertedAccountId(String ConvertedAccountId) {
        this.ConvertedAccountId = ConvertedAccountId;
    }

    // ConvertedContactId
    private String ConvertedContactId;

    @JsonProperty("ConvertedContactId")
    public String getConvertedContactId() {
        return this.ConvertedContactId;
    }

    @JsonProperty("ConvertedContactId")
    public void setConvertedContactId(String ConvertedContactId) {
        this.ConvertedContactId = ConvertedContactId;
    }

    // ConvertedOpportunityId
    private String ConvertedOpportunityId;

    @JsonProperty("ConvertedOpportunityId")
    public String getConvertedOpportunityId() {
        return this.ConvertedOpportunityId;
    }

    @JsonProperty("ConvertedOpportunityId")
    public void setConvertedOpportunityId(String ConvertedOpportunityId) {
        this.ConvertedOpportunityId = ConvertedOpportunityId;
    }

    // IsUnreadByOwner
    private Boolean IsUnreadByOwner;

    @JsonProperty("IsUnreadByOwner")
    public Boolean getIsUnreadByOwner() {
        return this.IsUnreadByOwner;
    }

    @JsonProperty("IsUnreadByOwner")
    public void setIsUnreadByOwner(Boolean IsUnreadByOwner) {
        this.IsUnreadByOwner = IsUnreadByOwner;
    }

    // Jigsaw
    private String Jigsaw;

    @JsonProperty("Jigsaw")
    public String getJigsaw() {
        return this.Jigsaw;
    }

    @JsonProperty("Jigsaw")
    public void setJigsaw(String Jigsaw) {
        this.Jigsaw = Jigsaw;
    }

    // JigsawContactId
    private String JigsawContactId;

    @JsonProperty("JigsawContactId")
    public String getJigsawContactId() {
        return this.JigsawContactId;
    }

    @JsonProperty("JigsawContactId")
    public void setJigsawContactId(String JigsawContactId) {
        this.JigsawContactId = JigsawContactId;
    }

    // EmailBouncedReason
    private String EmailBouncedReason;

    @JsonProperty("EmailBouncedReason")
    public String getEmailBouncedReason() {
        return this.EmailBouncedReason;
    }

    @JsonProperty("EmailBouncedReason")
    public void setEmailBouncedReason(String EmailBouncedReason) {
        this.EmailBouncedReason = EmailBouncedReason;
    }

    // EmailBouncedDate
    private org.joda.time.DateTime EmailBouncedDate;

    @JsonProperty("EmailBouncedDate")
    public org.joda.time.DateTime getEmailBouncedDate() {
        return this.EmailBouncedDate;
    }

    @JsonProperty("EmailBouncedDate")
    public void setEmailBouncedDate(org.joda.time.DateTime EmailBouncedDate) {
        this.EmailBouncedDate = EmailBouncedDate;
    }

    // Account__c
    private String Account__c;

    @JsonProperty("Account__c")
    public String getAccount__c() {
        return this.Account__c;
    }

    @JsonProperty("Account__c")
    public void setAccount__c(String Account__c) {
        this.Account__c = Account__c;
    }

    // Timezone__c
    @XStreamConverter(PicklistEnumConverter.class)
    private TimezoneEnum Timezone__c;

    @JsonProperty("Timezone__c")
    public TimezoneEnum getTimezone__c() {
        return this.Timezone__c;
    }

    @JsonProperty("Timezone__c")
    public void setTimezone__c(TimezoneEnum Timezone__c) {
        this.Timezone__c = Timezone__c;
    }

}
