/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon May 09 18:02:06 CET 2016
 */
package org.exoplatform.salesforce.integ.connector.entity;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
public enum StatusEnum {

    // Attempted
    ATTEMPTED("Attempted"),
    // Bad Data
    BAD_DATA("Bad Data"),
    // Cloud user
    CLOUD_USER("Cloud user"),
    // Cold
    COLD("Cold"),
    // Community user
    COMMUNITY_USER("Community user"),
    // Contacted
    CONTACTED("Contacted"),
    // Duplicate
    DUPLICATE("Duplicate"),
    // No Potential
    NO_POTENTIAL("No Potential"),
    // Open
    OPEN("Open"),
    // Passive Recycle
    PASSIVE_RECYCLE("Passive Recycle"),
    // Qualified
    QUALIFIED("Qualified"),
    // Raw Lead
    RAW_LEAD("Raw Lead"),
    // Re-open
    RE_OPEN("Re-open"),
    // Recycle
    RECYCLE("Recycle"),
    // Sales Refused Lead
    SALES_REFUSED_LEAD("Sales Refused Lead");

    final String value;

    private StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
        for (StatusEnum e : StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
