/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 17 15:09:19 CET 2016
 */
package org.exoplatform.salesforce.integ.connector.entity;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Timezone__c
 */
public enum TimezoneEnum {

    // GMT
    GMT("GMT"),
    // GMT+10
    GMT10("GMT+10"),
    // GMT+12
    GMT12("GMT+12"),
    // GMT+14
    GMT14("GMT+14"),
    // GMT+2
    GMT2("GMT+2"),
    // GMT+4
    GMT4("GMT+4"),
    // GMT+6
    GMT6("GMT+6"),
    // GMT+8
    GMT8("GMT+8"),
    // GMT-10
    GMT_10("GMT-10"),
    // GMT-12
    GMT_12("GMT-12"),
    // GMT-2
    GMT_2("GMT-2"),
    // GMT-4
    GMT_4("GMT-4"),
    // GMT-6
    GMT_6("GMT-6"),
    // GMT-8
    GMT_8("GMT-8");

    final String value;

    private TimezoneEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static TimezoneEnum fromValue(String value) {
        for (TimezoneEnum e : TimezoneEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
