/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 20 18:33:34 CET 2016
 */
package org.exoplatform.salesforce.integ.connector.entity;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject User
 */
@JsonIgnoreProperties(ignoreUnknown=true)
@XStreamAlias("User")
public class User {

    private String id;

    @JsonProperty("Id")
    public String getId() {
        return this.id;
    }

    // LastName
    private String LastName;

    @JsonProperty("LastName")
    public String getLastName() {
        return this.LastName;
    }

    @JsonProperty("LastName")
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    // FirstName
    private String FirstName;

    @JsonProperty("FirstName")
    public String getFirstName() {
        return this.FirstName;
    }

    @JsonProperty("FirstName")
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

}
